dist: xenial
language: python
addons:
    apt:
        packages:
            graphviz
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip freeze
    - ./prep_data.sh
script: ./tests.sh
